### PR TITLE
Full suggest API (did you mean and completion support)

### PR DESCRIPTION
**Pull request by fabn**
I rebased both #857 and #777 against the current master with feature from both branches.

@fbatista branch based his work on standalone suggest api, while @marc-villanueva added it to the search DSL. 

I think that both approaches are valid and needed so I merged them in a single PR.

For instance while doing a search it may be good to send a phrase suggestion request with the search itself in order to show a 'did you mean' warning in search results, while if you're implementing an autocompletion box the standalone API will fit best.

I've also added some integration tests and documentation in tire-dsl.rb document, I hope this will be finally merged and released in (re)tire.

Let me know if there is something wrong or that needs improving.

### CODE REVIEW

**Comment by fbatista** [comment]
Great Job Fabio!

**Comment by marc-villanueva** [comment]
Thank you for this!

**Comment by anthonator** [comment]
Any updates on this?

**Comment by fbatista** [comment]
I believe this branch got pretty much everything we need. I'd love for @karmi to take a look and hopefully merge this into the master tree. I'm going to drop the other one https://github.com/karmi/retire/pull/857 .

**Comment by karmi** [comment]
I'll try to have a look into it over holidays, been too busy with the new gem in the past couple of weeks...

**Comment by kjeremy** [comment]
@karmi any news on this?

**Comment by karmi** [comment]
Given the ridiculous delay on my side, I'll probably rebase, squash, edit all the commits myself.

**Comment by karmi** [comment]
@fbatista @fabn @marc-villanueva Guys, many thanks for this! I can see from the Git log it has been quite laborious to integrate all the different approaches and pull requests. Grazie, gracias, obrigado!

Sorry to anybody waiting for this for so long. I've been working on the elasticsearch-ruby library, and the upcoming elasticsearch-rails library.

**Comment by ches** [comment]
:tada:

**Comment by fabn** [comment]
@karmi Thanks for merging this. One question is there any public version of the upcoming elasticsearch-rails library?

**Comment by karmi** [comment]
Should be soon, either tomorrow or on Monday, depending how (un)happy I am :)

**Pull request closed without merging**
