### PR TITLE
added read_attribute_for_serialization to result item

### PR DESCRIPTION
**Pull request by lasssim**
I added the method **read_attribute_for_serialization** to the result item to support active model serializers.

### CODE REVIEW

**Comment by karmi** [comment]
Can you please check with https://github.com/karmi/tire-contrib/pull/15 and https://github.com/ResumUP/tire_am_serializers, and also add test cover for the feature?

**Comment by lasssim** [comment]
hi,

sorry for the missing test. i just added them.

the tire_am_serializers gem only helps with autodetecting a serializer as far as i can tell from skimming the code.

active model serializers uses the read_attribute_for_serialization method to retrieve attributes from the objects it serializes. this is the part from active model serializers (activemodel-3.2.11/lib/active_model/serialization.rb:100)

``` ruby
      # Hook method defining how an attribute value should be retrieved for
      # serialization. By default this is assumed to be an instance named after
      # the attribute. Override this method in subclasses should you need to
      # retrieve the value for a given attribute differently:
      #
      #   class MyClass
      #     include ActiveModel::Validations
      #
      #     def initialize(data = {})
      #       @data = data
      #     end
      #
      #     def read_attribute_for_serialization(key)
      #       @data[key]
      #     end
      #   end
      #
      alias :read_attribute_for_serialization :send

```

br, simon

**Comment by mulderp** [comment]
Hm.. I can't confirm this commit to make my ActiveModelSerializer work. I am using:

```
    movies = Movie.search(params[:q], :load => true)
    render :json => movies, :each_serializer => MovieSerializer
```

But get a:

```
   NoMethodError (undefined method `<=' for false:FalseClass)
```

Let me know, if I can test some variation.

**Comment by karmi** [comment]
@lister Sorry for the ridiculous delay! Merged the patch and added some tests for ActiveModel::Serializers (d2263fb)

@mulderp Could you try again? Notice (d2263fb), that you need to specifically include the support in `Tire::Results::Item`, if you'd need to serialize those. Your models should work fine I guess -- please paste the fuller backtrace for the error.

**Pull request closed without merging**
