### PR TITLE
Add support for text queries to the DSL

### PR DESCRIPTION
**Pull request by woodhull**
There is a quick unit test for this as well, but I was unable to execute it because I had trouble getting the test suite working. 

Small addition to support: 
http://www.elasticsearch.org/guide/reference/query-dsl/text-query.html

Thanks, 

Nathan

### CODE REVIEW

**Comment by karmi** [comment]
Hi Nathan, could you add a simple integration test as well? Also, could you post here the troubles with the test suite? It should really be working with no problems...

**Comment by gedwards** [comment]
The tests, including Nathan's addition, all pass after running:
bundle install --path .bundle
bundle exec rake test

**Comment by karmi** [comment]
@woodhull: Could you add some simple integration test, please? If you have troubles running the tests, bug me here or on IRC!

**Comment by woodhull** [comment]
Karmi, 

Just added a quick integration test!

-Nathan

**Comment by karmi** [comment]
Nathan, I'm terribly sorry it took me song long to process the patch. It's now included with some cleanups in a7a62d6f26a307ea61f5076864637c2a2fc32165. Thanks!

**Pull request closed without merging**
