### PR TITLE
Search#to_hash Bug when initialized with Payload

### PR DESCRIPTION
**Pull request by 1st8**
Hi,

while trying to get a nested query to work, I stumbled over the Bug demonstrated in the.
I appended a simple fix for this, too.

This is my first pull request, please excuse any mistakes I might have made.

Other topic:
Are you planning on nested query integration?
Might have to implement it soon, would be cool if I could contribute to your efforts.

Regards
Christoph

### CODE REVIEW

**Comment by dylanahsmith** [comment]
I also have a fix for this in pull request #292.

**Comment by konsti** [comment]
:+1: This is a really annoying bug if you want to pass raw ElasticSearch queries via the payload.
Any call to `to_curl`, `to_json` are stripping the payload from the options. Even without calling these functions in your code the log is empty afterwards.

**Comment by karmi** [comment]
Hey, I believe this was closed by karmi/tire@cb30f52, can you check?

**Comment by karmi** [comment]
Closing, no reply.

**Pull request closed without merging**
