### PR TITLE
Pooled curb v1

### PR DESCRIPTION
**Pull request by brupm**
- Uses https://github.com/jugend/common-pool to allow for high-performance HTTP requests for a multi-threaded environment.
- Properly handles `Curl::Err::MultiBadEasyHandle`
- I will write tests if you think there's validity in this PR.

### CODE REVIEW

**Comment by karmi** [comment]
Hi, great! Can you please squash the commits into one and also remove the dependency from the gemspec?

**Comment by brupm** [comment]
@karmi all done. The dependency appears to be required, otherwise all will not boot. @karmi Am I missing something?

**Comment by karmi** [comment]
> The dependency appears to be required, otherwise all will not boot

It's the same thing as with eg. the Faraday client -- you need to require the dependency externally, eg. in an application initializer, etc. On a second thought, can you please move the pull request from here to [tire-contrib](https://github.com/karmi/tire-contrib)?

**Comment by brupm** [comment]
https://github.com/karmi/tire-contrib/pull/18

**Pull request closed without merging**
