### PR TITLE
Adapter specific importing

### PR DESCRIPTION
**Pull request by jwaldrip**

### CODE REVIEW

**Comment by jwaldrip** [comment]
Looking at this further, I wonder if this should just be added to index#import. Or have a more sophisticated way of managing this.

**Comment by jwaldrip** [comment]
@karmi I am sure your week has been busy. What are your thoughts on this request?

**Comment by jwaldrip** [comment]
@karmi I think this needs more thought on my end. I will think deeper on it and provide a more elegant solution.

**Comment by karmi** [comment]
@jwaldrip The basic idea is OK!, I'll take the code and take it from there, it needs only some reshaping.

**Comment by karmi** [comment]
Hi Jason, I took the idea and added support for different importing strategies. Tested only manually, don't have the bandwith to add a full fledged test coverage at the moment.

**Pull request closed without merging**
