### PR TITLE
Support for constant score query

### PR DESCRIPTION
**Pull request by jockee**

### CODE REVIEW

**Comment by xeago** [comment]
You should implement this in [tire-contrib](https://github.com/karmi/tire-contrib). It is more likely to be accepted there.

**Comment by karmi** [comment]
Hey @jocke12, nice -- could you add a unit test for the added query, and possible a simple integration test demonstrating the behaviour?

**Comment by karmi** [comment]
@jocke12 Also, indeed, [`tire-contrib`](https://github.com/karmi/tire-contrib/tree/master/lib/tire/queries) is a better place for the pull request, still need to maintain the gem slim at this point...

**Comment by karmi** [comment]
Closing, waiting for pull request on `tire-contrib`.

**Comment by brupm** [comment]
Hi any update on this? Has it been merged into tire-contrib?

**Comment by jockee** [comment]
@brupm https://github.com/karmi/tire/pull/648 has been merged.

**Pull request closed without merging**
