### PR TITLE
Add JavaScript Runtime to example

### PR DESCRIPTION
**Pull request by dariusgm**
This will prevent the example to thow errors.

### CODE REVIEW

**Comment by karmi** [comment]
Hey, this is strange, shouldn't it be handled by Rails itself?

**Comment by dariusgm** [comment]
I think the example App should run instantly. As I downloaded it, it didn't work. After adding the run time it worked. I don't know if this should be handled by the user or be inside the example.

**Comment by karmi** [comment]
Yes, the example app should definitely run out of the box. But it does on my machine:

```
$ gem list therubyracer

*** LOCAL GEMS ***


$ rails new searchapp -m https://raw.github.com/karmi/tire/master/examples/rails-application-template.rb
...
=> Rails 3.2.13 application starting in development on http://0.0.0.0:3000
```

What error do you receive?

**Comment by dariusgm** [comment]
Using Ruby 2.0-p0 as Run time Environment create this error while launching the rails server. The Rake Task Abort with the message:
<code>Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (...)</code> - same while indexing the database.

**Comment by karmi** [comment]
Actually, on Ruby 2.0 I'm getting an error related to https:

```
ruby/2.0.0/net/http.rb:917:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
```

I wouldn't like to add JS runtime to the example, since this is something Rails should take care of. Closing this for the moment, and will have a look on how to solve the SSL issues on 2.0...

**Pull request closed without merging**
