### PR TITLE
Added support for Suggest API

### PR DESCRIPTION
**Pull request by marc-villanueva**
Added support for Suggest API - http://www.elasticsearch.org/guide/reference/api/search/suggest/

Tested against 0.90.1.  I also fixed a couple of existing integration tests were broken against this version.

### CODE REVIEW

**Comment by phoet** [comment]
@marc-villanueva your changes are breaking the ruby 1.8.7 builds on travis. could you use old hash syntax in the tests, so that the travis build passes?

**Comment by finalarena** [comment]
Any chance this can be merged now?

**Comment by tharry** [comment]
Is suggest api going to be added to tire anytime soon?

**Comment by karmi** [comment]
@marc-villanueva Can you please get in touch @fbatista which contributed suggest in #857 as well? Maybe you can combine the approaches and you can help him.

**Pull request closed without merging**
