### PR TITLE
[Bug Fix] to_json must accept optional generator

### PR DESCRIPTION
**Pull request by bcoe**
[Bug Fix] Some JSON libraries require an optional generator be passed into the to_json method. This makes the addition of multi_json solve a more general set of problems.

### CODE REVIEW

**Comment by karmi** [comment]
Yeah, this is ActiveSupport, most probably, where `to_json` takes a `Hash` of options. However, I don't get any error for this, since this options Hash is optional. Do you have a specific error, gem, etc., where it fails?

**Comment by bcoe** [comment]
It fails for me in my production Rails 3 environment with an error like this: (1 argument provided 0 expected). This exception is raised in all the the Tire classes with the to_json method. Not quite sure which library is causing this exception, my guess would be it's activesupport (3.0.7) -- simply accepting a parameter and throwing it away allows me to run example/dsl.rb in production.

**Comment by bcoe** [comment]
[REQUEST FAILED] ArgumentError 
ArgumentError: wrong number of arguments (1 for 0)
    from /usr/lib/ruby/gems/1.8/gems/tire-0.1.6/lib/tire/search.rb:94:in `to_json'
    from /usr/lib/ruby/gems/1.8/gems/tire-0.1.6/lib/tire/search.rb:94:in`to_json'
    from /usr/lib/ruby/gems/1.8/gems/tire-0.1.6/lib/tire/search.rb:81:in `to_curl'
    from /usr/lib/ruby/gems/1.8/gems/tire-0.1.6/lib/tire/search.rb:74:in`perform'
    from /usr/lib/ruby/gems/1.8/gems/tire-0.1.6/lib/tire/dsl.rb:10:in `search'
    from (irb):10
    from /usr/local/lib/site_ruby/1.8/rubygems/exceptions.rb:19

There you go :) accepting the parameters and throwing them out has been tested for me and fixes this issue.

**Comment by karmi** [comment]
This is really weird, since we run a Rails 3.0.7 app in production as well, and the demo app (`rails new searchapp -m https://github.com/karmi/tire/raw/master/examples/rails-application-template.rb`) runs fine as well. I'll have another look into this...

**Comment by bcoe** [comment]
Hmm, I think it's actually the json (1.5.1) gem that expects the generator -- try against this in irb. Again, accepting the optional parameter solves this incompatibility issue.

Any ways, time to go start work on my own JSON library -- that will solve the problem!

**Comment by karmi** [comment]
I am still not convinced this is the case. Try to reproduce it like this.

First, generate a demo Rails 3.0.7 app:

```
rails new searchapp -m https://github.com/karmi/tire/raw/master/examples/rails-application-template.rb
```

Then, change the JSON library to the "json" gem in your `Gemfile`:

```
gem "json"
```

and load the JSON library in your `application.rb`:

```
require 'rails/all'
require 'json'
```

Now, does searching in the app work for you or not? Because in my case, I get no `ArgumentError`. And rightly so, because the "json" gem really does have any arguments for `to_json` as optional. Evidence: https://github.com/flori/json/blob/master/lib/json/pure/generator.rb#L257

So, _if_ it does fail for you in the example app, then we'll dig into this deeper. I'm rather reluctant to add all the throwaway arguments to all the `to_json` methods. I'm happy that _Tire_ does not depend on "yajl" now, but wouldn't like to over-compicate stuff.

**Comment by bcoe** [comment]
Try the 'json' dependency without requiring 'rails/all'. The only dependencies I'm including in irb are:

require 'rubygems'
require 'json'
require 'tire'

**Comment by karmi** [comment]
Yeah, I've found this as well on my own. Seems like requiring Rails, ie. requiring ActiveSupport somehow makes the good ole' "json" gem to behave... I think adding the throwaway args to `to_json` methods in _Tire_ is the only solution, really.

**Comment by bcoe** [comment]
Lol, with regards to my blog post, I hope there's no hard feelings -- really wasn't trying to go after your library :) I'm going to keep using/patching it.

**Comment by karmi** [comment]
No, no hard feelings whatsoever! I just felt I should reply there, since a friend referred me to your article. I think you were too harsh on Ruby and its ecosystem, so I replied. And the more I think about the more I wonder why `to_json` methods in Tire with arity==0 don't fail at all times :)

**Comment by bcoe** [comment]
My branch has diverged fairly far from master, don't see a point to keeping this open.

**Comment by znbailey** [comment]
I just spun up a new rails project using tire and I'm running into this issue, though the error is slightly different:

wrong number of arguments (2 for 1)

stack is:

activesupport (3.1.2) lib/active_support/core_ext/object/to_json.rb:19:in `to_json'
tire (0.3.11) lib/tire/index.rb:296:in`to_json'
tire (0.3.11) lib/tire/index.rb:296:in `convert_document_to_json'
tire (0.3.11) lib/tire/index.rb:54:in`store'
tire (0.3.11) lib/tire/index.rb:8:in `instance_eval'
tire (0.3.11) lib/tire/index.rb:8:in`initialize'

What's the recommended approach to getting everything playing nice together? This project literally has one controller file in it and that's it (no complicated dependencies). Running ruby 1.9.2 and the only gems in my gemfile are rails, tire, and sqlite3

Thanks!

**Comment by znbailey** [comment]
Looks like adding a dependency on yajl-ruby in my Gemfile and then adding:

require 'yajl/json_gem'

before

require 'rails/all' 

in my application.rb fixed things up. Not entirely sure why as it seems like multi_json should be falling back to the standard json gem?

**Comment by karmi** [comment]
Thanks for the report -- this issue is really hard to hunt down, since different components overload JSON serialization/behaviour differently. Could you try to to change the Hash#to_json definition in https://github.com/karmi/tire/blob/master/lib/tire/rubyext/hash.rb#L3 to:

``` ruby
def to_json(options = nil)
  MultiJson.encode(self)
end unless respond_to?(:to_json)
```

**Pull request closed without merging**
