### PR TITLE
default_operator

### PR DESCRIPTION
**Pull request by seejohnrun**
Added support to #string for :default_operator

### CODE REVIEW

**Comment by karmi** [comment]
Hi, thanks, squashed and merged in karmi/tire@6a3b4f3. However, it was later superseded by @vhyza's patch at karmi/tire@7d57038 :)

**Comment by seejohnrun** [comment]
Cool - I was going to make that move but was assuming you had excluded the rest of the operators for a reason.
Thanks for the gem, keep up the great work

**Comment by karmi** [comment]
No, I just try to stick "implement only what you need" philosophy. In almost any case when I diverged from that it was pain :)

**Comment by seejohnrun** [comment]
Yeah its definitely better for the gem too, especially as ES expands their API

**Pull request closed without merging**
