### PR TITLE
Add support for geo distance facets

### PR DESCRIPTION
**Pull request by robinbrandt**
This pull request adds implementation and tests for geo distance facets to tire, see http://www.elasticsearch.org/guide/reference/api/search/facets/geo-distance-facet for more details.

Thanks for your work on tire. We use it at Stuffle (http://stuffle.it) and it's great how little effort was needed to integrate ElasticSearch.

Cheers,
Robin

### CODE REVIEW

**Comment by robinbrandt** [comment]
@karmi any thoughts?

**Comment by karmi** [comment]
@robinbrandt I like it, thanks!, will try to process it as soon as possible...

**Comment by karmi** [comment]
@robinbrandt By the way, what do you think about #283? Do you use geo filtering as well?

**Comment by robinbrandt** [comment]
We don't use it yet but probably in a couple of hours ;) I have to play around with it a bit more but my first expression was that geo distance is just another filter and the filtering DSL is flexible enough to support it so there's no need for another special geo syntax. 

But I'll give it a try. When I find out I was wrong, I'll grab the ticket, ok?

**Comment by robinbrandt** [comment]
Hi @karmi !

Any idea if this could make it into the next tire release?

**Comment by karmi** [comment]
@robinbrandt Sorry it took so long! Merged and pushed, thanks for a great patch! I'll include it in the next release, once I solve other hanging issues, will release probably tommorrow.

**Comment by robinbrandt** [comment]
No problem, thanks for your work.

**Pull request closed without merging**
