### PR TITLE
More index store options

### PR DESCRIPTION
**Pull request by fcheung**
Support all the option you can pass when indexing individually or in bulk.

### CODE REVIEW

**Comment by jerryluk** [comment]
Would Love to have parent support. +1

**Comment by mattiassvedhem** [comment]
+1.

**Comment by fcheung** [comment]
Yeah bulk_store is a little messy. It's got a lot in common with multi_search if my memory is correct so there is probably an opportunity to find a nice solution to deal with both.

**Comment by karmi** [comment]
Closing in favour of more complete implementation...

**Pull request closed without merging**
