### PR TITLE
support custom filters score

### PR DESCRIPTION
**Pull request by fcheung**
Adds support for the custom filters score query type ( http://www.elasticsearch.org/guide/reference/query-dsl/custom-filters-score-query/ )

### CODE REVIEW

**Comment by brupm** [comment]
This is already in tire-contrib https://github.com/karmi/tire-contrib/blob/master/lib/tire/queries/custom_filters_score.rb @fcheung

**Comment by karmi** [comment]
@fcheung I've added the patch, and also added a more DSL-ish variant. I think the tire-contrib version is superior, as @brupm noted :), can you check if it satisfies your use case? I'll move it over from contrib to core I guess.

**Comment by fcheung** [comment]
I hadn't spotted the tire-contrib version - It hadn't ocurred to me to look there. Looks fine to me.

**Comment by karmi** [comment]
@fcheung Embarassingly enough, I forgot as well :) Will create a mashup of these and push it.

**Pull request closed without merging**
