### PR TITLE
Added open/close index functionality.

### PR DESCRIPTION
**Pull request by bcoe**
Added _open/_close index functionality. This is good for multitenant applications where not all lucene indexes are open at once.

I need this for my production deployment of elasticsearch, would love to use the canonical project, and not my fork :)

### CODE REVIEW

**Comment by bcoe** [comment]
The yajl-ruby library was causing major issues in my Rails deployment. The main problem being that the :methods key appears to not be supported in their JSON extension. I modified Tire so that it defaults to the 'json' gem by default, but can still use yajl if available (and working). I also found one other bug in my production deployment related to arrays having a 'to_hash' method punched onto them, I submitted a patch for this -- Tire is working great for me now in production.

**Comment by karmi** [comment]
Hi, thanks! I've squashed the commits into into one, and edited. Merged in karmi/tire@d51f0cc1d143eb7907a1c30cd581335ad4babee0.

I am aware that the duplication in the execute > rescue > raise > ensure is quite dumb. However, I don't like having the wrapper method like you did there. There's certainly a better way, most probably in augmenting the `Client` class, which is only a thin wrapper for now.

**Comment by karmi** [comment]
Regarding the other two issues:

1/ Yes, forcing yajl on everybody is absolutely stupid. Rails now goes with the intridea/multi_json gem, so I'll follow suit.

2/ Wow, Array having a `to_hash` method? This is coming from some library? @floere corrected the previous check for `is_a?(Hash)` (which is what you should have used?), see commit tire@081eb36. I think we can return to previous version. Could you find the library which implements `Array#to_hash`?

**Comment by karmi** [comment]
OK, the yajl dependency removed in tire@90011cb4e1b3bb29666b75beb01ed50213029e78.

**Comment by bcoe** [comment]
Cool, yajl was causing issues for me :) 

I'm not quite sure what is punching to_hash onto an Array. But, I think relying on that method name to determine if something is a hash is a bit cavalier. It's just too loaded, i.e., it might refer to just creating an MD5 hash out of a non-hashmap object.

Thanks for the updates :)

**Comment by karmi** [comment]
>  relying on that method name to determine if something is a hash is a bit cavalier

LOL, definitely! I'll change it to the previous version, no harm by that and you'll be sorted.

**Comment by bcoe** [comment]
Thanks :) very much appreciated,

**Comment by karmi** [comment]
OK, all issues should be fixed and pushed at tire@v0.1.5, also released to Rubygems. Cheers!

**Pull request closed without merging**
