### PR TITLE
Kaminari pagination support

### PR DESCRIPTION
**Pull request by vwall**
Just some simple Kaminari additions with tests.

### CODE REVIEW

**Comment by karmi** [comment]
Hi, could you rebase the changes against the current master? If no, I'll do it.

**Comment by vwall** [comment]
Should be done already.

**Comment by karmi** [comment]
It's not, see the merge commit https://github.com/vwall/tire/commit/be6b61d7dbd3ceda01406ddb43b349031f27d850. No worries, I'll rebase that.

**Comment by vwall** [comment]
Whoops.  Sorry about that.  Should be good now.

**Comment by nickhoffman** [comment]
Hey guys. How is this patch meant to be used? With Kaminari and Tire loaded, _#paginate_ doesn't exist on Tire::Results::Collection objects:

``` ruby
irb> Product.tire.search('megatron').paginate
NoMethodError: undefined method `paginate' for #<Tire::Results::Collection:0xaccb2f8>
        from (irb):66
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.4/lib/rails/commands/console.rb:44:in `start'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.4/lib/rails/commands/console.rb:8:in `start'
        from /usr/local/rvm/gems/ruby-1.9.2-p0/gems/railties-3.0.4/lib/rails/commands.rb:23:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by nickhoffman** [comment]
Ack, nevermind! Please ignore that previous comment of mine.

**Comment by hahuang65** [comment]
What was the solution? I was not able to get this to work with either the .paginate or the .page methods.

**Comment by nickhoffman** [comment]
@hahuang65 _#paginate_ is usually used within a view, like this:

``` ruby
# app/controllers/products_controller.rb
def index
  @products = Product.tire.search "megatron"
end

# app/views/products/index.html.erb
paginate @products
```

**Comment by karmi** [comment]
Yeah, just implement `MyModel.paginate` as a thin wrapper around Kaminari, see https://github.com/karmi/tire/issues/48#issuecomment-1499519.

**Comment by plentz** [comment]
@karmi there's more things to be supported, like https://github.com/karmi/tire/issues/48#issuecomment-4589313. I think that @amatsuda could help us here.

**Pull request closed without merging**
