### PR TITLE
Added min_score support to search

### PR DESCRIPTION
**Pull request by edmundsalvacion**
- Add min_score method to Search
- Added min score context to tests

### CODE REVIEW

**Comment by karmi** [comment]
Hi, is it something you need or is it a "speculative" patch? :) Would you mind to create an extension to [_tire-contrib_](https://github.com/karmi/tire-contrib) for that?

**Comment by edmundsalvacion** [comment]
Hi, it's something I need. I could certainly move it over to tire-contrib.

**Comment by edmundsalvacion** [comment]
Question, do you have any guidelines on the modularity of items in tire-contrib?

Also, what do you see as appropriate to be in the main project vs contrib as far as the elasticsearch apis go?

**Comment by karmi** [comment]
Well, if I understand the [ES docs](http://www.elasticsearch.org/guide/reference/api/search/min-score.html) correctly, it returns only a portion of results where the score is above a certain threshold. That _may_ just what you wanted in a tiny slice of use-cases. Most times, you want to actually display _some_ results...

The ES docs say: _Note, most times, this does not make much sense, but is provided for advance use cases_.

This seems to me as cross the line between _core_ and _contrib_: core is what 80% people would use, _contrib_ is for specific/advanced/crazy stuff.

**Comment by karmi** [comment]
> Question, do you have any guidelines on the modularity of items in tire-contrib?

That's easy, just add/overload/etc anything in the Tire namespace, add tests, etc. See the [rails-logger](https://github.com/karmi/tire-contrib/blob/master/lib/tire/rails-logger.rb) extension for inspiration. The whole thing is modeled after [rack-contrib](https://github.com/rack/rack-contrib).

**Comment by karmi** [comment]
Hello @edmundsalvacion, can I help you with the `tire-contrib` integration? Ping me here or at the #elasticsearch IRC!

It should be very easy to transfer the code from core to contrib. I'll close the pull request here and wait for a pull request on contrib...

**Comment by timothyklim** [comment]
Hi, thanks for patch!

Why this patch is not included in core? Without this feature, search result is ugly(often).

+1 to core

**Comment by karmi** [comment]
> Why this patch is not included in core?

Because it's a great fit to contrib.

> Without this feature, search result is ugly(often).

What do you mean?

**Comment by timothyklim** [comment]
> What do you mean?

When you know that search result is not relevant when score below the value 0.5. Best way to hide irrelevant results is specify the "min_score".

> first day and first my usage experience of tire

After I've read tire manuals, I've started search "How to set minimum score?" and I found elastic guides and this pull request.

> That may just what you wanted in a tiny slice of use-cases. Most times, you want to actually display some results...

And we will have irrelevant results on the search page.

Thanks.

**Comment by karmi** [comment]
> When you know that search result is not relevant when score below the value 0.5. Best way to hide irrelevant results is specify the "min_score".

I still consider the case where you don't want to present _any results whatsoever_ to the user an edge case. I can't imagine it widely used; the computed `score` varies wildly and people are usually better at judging the results, refining their query, etc.

I look forward to see the pull request on [`tire-contrib`](https://github.com/karmi/tire-contrib)!

**Comment by sg552** [comment]
hi @Karmi, I am a Chinese user. Tire is great, but I didn't see the "min_score" function. Since in Chinese the street name is extremely complex to analyze. such as: "太阳宫", (which mean "sunny plaza") however without "min_score", most of the result is not relevant and below score 0.3.  so I think I need this option. 

I will commit the code to "tire-contrib". ( though I am monkeypatching the tire core ^_^ )

**Comment by axsuul** [comment]
I don't see a pull request on tire-contrib for this. Should I do this?

**Pull request closed without merging**
