### PR TITLE
prefix query

### PR DESCRIPTION
**Pull request by tobowers**
Hi,

Great work on Tire... I'll probably be going through and attempting to add a few more query types and maybe 1.9 support for tests, etc.  Hope this will be ok with you!

Anyway - here's my first one to support the prefix query type.

Thanks,

Topper

### CODE REVIEW

**Comment by karmi** [comment]
Hi, thanks!

> attempting to add a few more query types

yeah, feel fee to do so.

> and maybe 1.9 support for tests

not sure what you mean by that?

> here's my first one to support the prefix query type.

I'd like to have query types covered by integration tests as well, is it possible to add some?

Best,

Karel

**Comment by tobowers** [comment]
rcov isn't 1.9 compatible so bundle install doesn't work in ruby 1.9+

I don't see any integration tests for other query types... I'm looking in the test/integration directory and I only see query_string.  Am I just not seeing the location?

**Comment by karmi** [comment]
Ah, yes, best to delete the `rcov` then.

See eg. https://github.com/karmi/tire/blob/master/test/integration/range_queries_test.rb etc....

**Comment by tobowers** [comment]
added a integration test

**Comment by karmi** [comment]
@karmi @vhyza Bump!

**Comment by karmi** [comment]
@tobowers Sorry for the ridiculous delay...

**Comment by lucascaton** [comment]
When a new version (with prefix query) will be released?

**Comment by lucascaton** [comment]
?

**Pull request closed without merging**
