### PR TITLE
Nested Query support

### PR DESCRIPTION
**Pull request by unsay**
DSL support for nested queries on the already supported nested type.

> Nested objects/documents allow to map certain sections in the document indexed as nested allowing to query them as if they are separate docs joining with the parent owning doc.
> 
> One of the problems when indexing inner objects that occur several times in a doc is that “cross object” search match will occur.

http://www.elasticsearch.org/guide/reference/query-dsl/nested-query.html

### CODE REVIEW

**Comment by mhenrixon** [comment]
Love it, would be very nice to have this added and released!

**Comment by karmi** [comment]
Hi, looks good! I think a nice integration test for this feature is needed as a documentation of how to use in in the DSL.

Preferably with a good, non-synthetic example which demonstrate the pitfalls of not using `nested` query with “objects within arrays” scenario, something along the lines of https://gist.github.com/4253dde6dd369979c4e9. Doable?

**Comment by unsay** [comment]
Sure enough!

**Comment by karmi** [comment]
@unsay Not rushing you, just please ping me when you push changes so it doesn't get lost.

**Comment by bgadoury** [comment]
I just realized we really need this, so I'm very excited to see it so close to hitting master. Thanks @unsay and @karmi !

**Comment by unsay** [comment]
If anyone can bite off the request by @karmi, I'm obliged.

I won't be available to complete for 2 more weeks.

**Comment by unsay** [comment]
Back in the saddle. Will finish this up!

**Comment by bgadoury** [comment]
@unsay Any news? :)

**Comment by unsay** [comment]
Derp. I'll do it now. :)

**Comment by loren** [comment]
@unsay This feature would be very useful for me. Any update on when it might ship?

**Comment by unsay** [comment]
I'll have a complete test suite probably tomorrow. The core functionality hasn't changed.

**Comment by karmi** [comment]
@unsay Cool!

**Comment by unsay** [comment]
@karmi let me know!

**Comment by unsay** [comment]
@loren, sorry about the noise. HTH. https://github.com/unsay/tire/commit/82dc19e9c433c85805a2b3a9fb2546053e895453

**Comment by loren** [comment]
@unsay, it works wonderfully. I had a slightly more complex nested mapping with different analyzers on the sub-fields, and I'm going to put it here just in case someone else stumbles upon the nested syntax.

Thank you for exposing this very useful feature in ES.

 :mappings => {
            :position => {
              :_ttl => {:enabled => true},
              :properties => {
                :title => {:type => 'string', :analyzer => 'snowball'},
                :type => {:type => 'string'},
                :locations => {
                  :type => 'nested',
                  :properties => {
                    :city => {:type => 'string', :analyzer => 'whitespace'},
                    :state => {:type => 'string', :analyzer => 'keyword'}
                  }
                },
                :id => {:type => 'integer', :index => :not_analyzed, :include_in_all => false}
              }
            }
          }

**Comment by unsay** [comment]
@loren Great! Once this is merged in, I'll apply similar tests and examples for [nested filters](http://www.elasticsearch.org/guide/reference/query-dsl/nested-filter.html).

**Comment by karmi** [comment]
@unsay Hi, merged & pushed. I've retouched the code and tests a bit, and also decided to change the example in `tire-dsl.rb`, so it's more separated from the main example. Thanks!

**Comment by erlingwl** [comment]
I've just tested this, seems to work great, even with multiple levels of nesting.

**Pull request closed without merging**
