### PR TITLE
Add suggest completion support to tire

### PR DESCRIPTION
**Pull request by fbatista**
As per http://www.elasticsearch.org/guide/reference/api/search/completion-suggest/

I am aware there is another pull request on this subject: https://github.com/karmi/tire/pull/777 but it only implements the term and phrase suggest apis and not completion api wich me and my team needed at the time.

I'd like to hear @karmi and everyone else's opinion on how to proceed with merging the work me and @marc-villanueva did before advancing further.

I know some of the pending tasks for this branch to be in a mergeable state are:
- use ruby 1.8 hashes 
- Fix tests for elasticsearch v0.90.1 
- Write integration tests

### CODE REVIEW

**Comment by mahemoff** [comment]
+1 great to see this

**Comment by karmi** [comment]
Hi @fbatista, this looks great -- although Tire has been "retired" recently, this is probably worth to add it. I'd like to ask you for two things:
- Could you add a bit of documentation to the source, with a note of what is supported and not
- Could you add a section about the suggester to the https://github.com/karmi/retire/blob/master/examples/tire-dsl.rb page
- Could you add integrations tests, which would demonstrate the feature in an immediately usable way (ie. search results with suggest, using DSL, etc)

**Comment by fbatista** [comment]
Thanks @karmi for the feedback, i'll get on to it as soon as i can.

**Comment by fabn** [comment]
@fbatista Any news on this?

**Comment by karmi** [comment]
@fbatista @fabn @marc-villanueva Guys, many thanks for this! I can see from the Git log it has been quite laborious to integrate all the different approaches and pull requests. Grazie, gracias, obrigado!

Sorry to anybody waiting for this for so long. I've been working on the [`elasticsearch-ruby`](https://github.com/elasticsearch/elasticsearch-ruby) library, and the upcoming `elasticsearch-rails` library.

**Pull request closed without merging**
