### PR TITLE
Should be `tire`, not `index` (README)

### PR DESCRIPTION
**Pull request by justinko**

### CODE REVIEW

**Comment by brupm** [comment]
It should be `index`

**Comment by karmi** [comment]
Actually, both are possible :) But in the context, the change suggested by @justinko is correct, since we want to use the newly added ["polymorphic" import](https://github.com/justinko/tire/blob/master/lib/tire/model/import.rb) strategies.

**Comment by brupm** [comment]
I stand corrected, didn't know about polymorphic import

**Comment by justinko** [comment]
Well let's merge this muthafucka! (Samuel L. Jackson voice)

**Comment by karmi** [comment]
Actually, when reading the passage in context, `Article.index.import` is right -- it communicates clearly that every `Tire::Index` object has an `import` method, and you can pass a collection (`Enumerable`) to it.

In contrast, `Article.import`, will try to pick up a strategy for handling loading the records.

Bottom line, current wording is correct, but we should advertise the strategies more in the README, not just say “depending on the setup of your model ...”.

**Pull request closed without merging**
