### PR TITLE
More like this search ability is added

### PR DESCRIPTION
**Pull request by orbanbotond**
Hi,

I added the more_like_this search ability on a new branch.

### CODE REVIEW

**Comment by karmi** [comment]
Hi, this functionality is supported by the `tire-contrib` library, https://github.com/karmi/tire-contrib/blob/master/lib/tire/queries/more_like_this/more_like_this.rb

**Comment by brupm** [comment]
Maybe there should be a warning in the Tire readme about the existence of tire-contrib

**Comment by karmi** [comment]
@brupm There is: https://github.com/karmi/tire#extensions-and-additions, but I agree it needs some force to scroll that much down :)

**Comment by orbanbotond** [comment]
Oh... I see now :) Thanks. May I close the issue?

**Comment by karmi** [comment]
@orbanbotond Yes, please...

**Pull request closed without merging**
