### PR TITLE
Support for PUT mappings

### PR DESCRIPTION
**Pull request by fabiob**
Recently I had to make a change to my mappings. I usually just drop my indexes and recreate them, but they're currently huge and the change was so small… So I added support for the Put Mapping API, as documented on http://www.elasticsearch.org/guide/reference/api/admin-indices-put-mapping.html

### CODE REVIEW

**Comment by fabiob** [comment]
Just found https://github.com/karmi/tire/pull/194, I think his code has better quality.

**Comment by karmi** [comment]
Hi, thanks. Yes, Dylan's version seems to be more complete, but there are still unresolved issues with handling conflicts, possibly merging them, etc etc. I have to focus on this. In the meantime, I'd advise to just use eg. `Tire::Configuration.client` to send some Hash down he wire to ES.

**Comment by karmi** [comment]
@fabiob Sorry, for the delay. Similar to #194, let's close this until there's a more feature complete implementation, with handling/ignoring conflicts, etc?

**Comment by karmi** [comment]
Closing in favour of a more complete implementation.

**Comment by alan** [comment]
@karmi has this been implemented or is it still not done?

**Comment by karmi** [comment]
@alan No, please see the discussion.

**Comment by alan** [comment]
Yes, saw it, just wondered if it had been implemented in another branch / pull request that I might have missed.

**Comment by karmi** [comment]
@alan Not yet :)

**Comment by JamesHarrison** [comment]
@karmi https://github.com/karmi/tire/pull/520 seems to do the trick - any chance of a merge?

**Pull request closed without merging**
