### PR TITLE
implement min_score and track_scores search options

### PR DESCRIPTION
**Pull request by fcheung**

### CODE REVIEW

**Comment by fcheung** [comment]
D'oh, just seen a bunch of other issues about support various es options and the ugliness of doing it piece by piece

**Comment by plentz** [comment]
-1 (for the same reason that @fcheung wrote :)

**Comment by raldred** [comment]
Shame, I would really like to be able to enable various options like track_scores that cannot be added to the search hash without providing the full payload.

**Comment by karmi** [comment]
Frederick, terribly sorry about the delay. Both the `min_score` and `track_scores` features are pushed now.

**Comment by karmi** [comment]
- The `parent` URL support was recently added in karmi/tire@12a0fed, 
- the `nested` query is being worked on in karmi/tire#475, focusing on nice, demonstrative integration tests,
- the `custom_filters_score` sounds nice, but needs both unit and integration tests to demonstrate the feature

**Comment by karmi** [comment]
Update, `custom_filters_score` is implemented in Tire Contrib, https://github.com/karmi/tire-contrib/blob/master/lib/tire/queries/custom_filters_score.rb

**Pull request closed without merging**
