### PR TITLE
*Slight* README change

### PR DESCRIPTION
**Pull request by mando**
little typo on the example facet call

### CODE REVIEW

**Comment by karmi** [comment]
Alas, that is not a typo :)

Notice the difference between `@search.results.facets`, which give you the counts and metadata from _ElasticSearch_ and the `@search.facets`, which gives you the facet definitions...

**Comment by karmi** [comment]
@mando Ping. Closing this?

**Comment by mando** [comment]
Yup - I apparently can't read.

Please don't tell anyone ;).

**Comment by karmi** [comment]
No worries! :) (The interface should make it probably a bit easier to distinguish anyway...)

**Pull request closed without merging**
