### PR TITLE
add possibility to bind the raw results to the eager loaded model

### PR DESCRIPTION
**Pull request by phoet**

### CODE REVIEW

**Comment by karmi** [comment]
Hey, what's the reasoning for this? Something like _Sunspot_'s `each_with_hit`, where you'd like both the ES JSON and the model from database? There has been some other discussion on that I believe.

**Comment by phoet** [comment]
i don't know sunspot, but i guess `each_with_hit` describes what it's supposed to do.

we use this to show meta-data, ie showing debug information like score etc.

**Comment by karmi** [comment]
Hey, visitor from the future :) I believe this is duplicate of karmi/tire#364 and karmi/tire#368 -- please have a look there. I think we need to augment the models (via the include hook) so they can automatically have search results appended to them etc.

Will close this in favour of more complete implementation?

**Comment by karmi** [comment]
Closing in favour of a more complete implementation.

**Comment by phoet** [comment]
@karmi just watching your talk at RuPy and see you talking about missing feedback :smile: 

i think i got unsubscribed from this issue. we currently have a custom fork of tire, i will try to update and contribute back our changes in the next weeks and have a look at the result decorator.

**Pull request closed without merging**
